In [60]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import altair as alt
from sklearn.decomposition import TruncatedSVD
from sklearn.linear_model import LinearRegression
from sklearn.preprocessing import StandardScaler
from sklearn.neighbors import KNeighborsRegressor
from sklearn.model_selection import train_test_split
from sklearn.metrics import mean_squared_error, mean_absolute_error

### Load Data

In [7]:
df = pd.read_csv("fashion3.csv")
df.head()

,Unnamed: 0.1,Unnamed: 0,item_id,category,waist,size,quality,cup size,hips,bra size,height_inches,length,fit,review_summary,review_text,polarity,reviewLen,wordCount
0,0,8490,159891,1,26.0,1,5.0,2.0,38.0,32.0,64.0,5.0,3,This dress. Is so amazing,This dress. Is so amazing. It just arrived tod...,0.392500,301,58
1,1,8493,159891,1,31.0,8,3.0,5.0,41.0,36.0,62.0,5.0,3,This dress looks great on,This dress looks great on. I'm a pretty curren...,0.186250,273,57
2,2,8521,160625,1,32.0,5,5.0,2.0,NaN,32.0,65.0,5.0,1,Used as my wedding dress,Used as my wedding dress and I LOVED it!PROS ...,0.172436,452,85
3,3,8523,160625,1,32.0,11,4.0,5.0,43.0,38.0,67.0,5.0,2,"I love this dress, it's b","I love this dress, it's beautiful ! Wore this ...",0.413839,581,125
4,4,8524,160625,1,28.0,7,5.0,3.0,32.0,34.0,65.0,5.0,3,I love this dress!!! I bo,I love this dress!!! I bought it specifically ...,0.400769,627,117

In [8]:
df.iloc[:,2:13]
col_lst = list(range(2,13))
col_lst.extend([15,17])
df = df.iloc[:,col_lst]
df_clean = df.dropna()

In [9]:
df_clean.head()

,item_id,category,waist,size,quality,cup size,hips,bra size,height_inches,length,fit,polarity,wordCount
0,159891,1,26.0,1,5.0,2.0,38.0,32.0,64.0,5.0,3,0.392500,58
1,159891,1,31.0,8,3.0,5.0,41.0,36.0,62.0,5.0,3,0.186250,57
3,160625,1,32.0,11,4.0,5.0,43.0,38.0,67.0,5.0,2,0.413839,125
4,160625,1,28.0,7,5.0,3.0,32.0,34.0,65.0,5.0,3,0.400769,117
7,160625,1,27.0,5,5.0,3.0,38.0,36.0,68.0,5.0,2,0.098889,42

# SVD

User's rating scores:

* `quality`, and `polarity`

Because both features have different scaling, we need to make sure that they have same scaling to combine them together

In [42]:
# Scaling range: [0,1]
# After scaling, take the average to get the overall score
col_lst = [4,11]
score = df_clean.iloc[:,col_lst].apply(lambda iterator: ((iterator - iterator.min())/(iterator.max() - iterator.min())).round(2))
score["avg"] = score.mean(axis=1)
score.head()

   quality  polarity    avg
0     1.00      0.69  0.845
1     0.50      0.59  0.545
3     0.75      0.70  0.725
4     1.00      0.70  0.850
7     1.00      0.54  0.770

In [43]:
 # Add user id and category
score.insert(0, "user_id", score.index + 1)
score.insert(1, "item_id", df_clean["category"])

In [44]:
# only keep the first three columns
score = score.iloc[:,0:3]
score.head()

   user_id  item_id  quality
0        1        1     1.00
1        2        1     0.50
3        4        1     0.75
4        5        1     1.00
7        8        1     1.00

In [45]:
score2 = score["quality"]

In [13]:
score = score.pivot(index='user_id', columns='item_id', values='quality')

In [16]:
score.head()

item_id     1   2   3   4
user_id
1        1.00 NaN NaN NaN
2        0.50 NaN NaN NaN
4        0.75 NaN NaN NaN
5        1.00 NaN NaN NaN
8        1.00 NaN NaN NaN

In [20]:
df_top = df_clean[['waist','height_inches','cup size', 'bra size']].copy()

In [34]:
score.fillna(0)

item_id     1    2    3     4
user_id
1        1.00  0.0  0.0  0.00
2        0.50  0.0  0.0  0.00
4        0.75  0.0  0.0  0.00
5        1.00  0.0  0.0  0.00
8        1.00  0.0  0.0  0.00
...       ...  ...  ...   ...
2090     0.00  0.0  0.0  0.00
2091     0.00  0.0  0.0  1.00
2094     0.00  0.0  0.0  1.00
2095     0.00  0.0  0.0  1.00
2096     0.00  0.0  0.0  0.75

[1455 rows x 4 columns]

In [46]:
X = df_top
y = score2

In [47]:
scaler = StandardScaler()

In [48]:
scaler.fit(X)

StandardScaler()

In [49]:
X_scaled = scaler.transform(X)

In [104]:
reg = KNeighborsRegressor(n_neighbors=15)

In [106]:
reg.fit(X_scaled,y)

KNeighborsRegressor(n_neighbors=15)

In [107]:
score["pred"] = reg.predict(X_scaled)

In [108]:
score

      user_id  item_id  quality      pred
0           1        1     1.00  0.700000
1           2        1     0.50  0.866667
3           4        1     0.75  0.866667
4           5        1     1.00  0.783333
7           8        1     1.00  0.816667
...       ...      ...      ...       ...
2089     2090        4     0.00  0.800000
2090     2091        4     1.00  0.750000
2093     2094        4     1.00  0.750000
2094     2095        4     1.00  0.783333
2095     2096        4     0.75  0.850000

[1455 rows x 4 columns]

In [109]:
X_scaled_train, X_scaled_test, y_train, y_test = train_test_split(X_scaled,y,test_size=0.2)

In [110]:
reg.fit(X_scaled_train,y_train)

KNeighborsRegressor(n_neighbors=15)

In [111]:
mean_squared_error(reg.predict(X_scaled_test),y_test)

0.06761550210003818

In [112]:
mean_squared_error(reg.predict(X_scaled_train),y_train)

0.055374427262313855

In [141]:
def get_scores(k):
    reg = KNeighborsRegressor(n_neighbors=k)
    reg.fit(X_scaled_train, y_train)
    train_error = mean_absolute_error(reg.predict(X_scaled_train), y_train)
    test_error = mean_absolute_error(reg.predict(X_scaled_test), y_test)
    return (train_error, test_error)

df_scores = pd.DataFrame({"k":range(1,150),"train_error":np.nan,"test_error":np.nan})

for i in df_scores.index:
    df_scores.loc[i,["train_error","test_error"]] = get_scores(df_scores.loc[i,"k"])

df_scores["kinv"] = 1/df_scores.k

In [142]:
ctrain = alt.Chart(df_scores).mark_line(color="#FF0000").encode(
    x = "kinv",
    y = "train_error"
)

In [143]:
ctest = alt.Chart(df_scores).mark_line(color="#045FB4").encode(
    x = alt.X("kinv",title='k-inverse'),
    y = "test_error"
)

In [144]:
ctrain+ctest

alt.LayerChart(...)