In [3]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

### Load Dataset

In [10]:
df = pd.read_csv("/Users/emicervantes/Desktop/FashionDataset/train.csv")
df.head()

,0,1,2,3,4,5,6,7,8,9,...,category,release_date,day,week,month,year,image_path,color,fabric,extra
0,0.004695,0.073239,0.061972,0.066667,0.046009,0.043192,0.026291,0.019718,0.012207,0.014085,...,long sleeve,2016-12-01,0.500000,0.923077,1.0,0.998514,PE17/00001.png,yellow,acrylic,hem
1,0.005634,0.109859,0.128638,0.135211,0.082629,0.098592,0.063850,0.052582,0.034742,0.138967,...,long sleeve,2016-12-01,0.500000,0.923077,1.0,0.998514,PE17/00002.png,brown,acrylic,hem
2,0.002817,0.207512,0.177465,0.095775,0.041315,0.030047,0.015023,0.006573,0.010329,0.005634,...,culottes,2016-12-02,0.666667,0.923077,1.0,0.998514,PE17/00003.png,blue,scuba crepe,hem
3,0.000939,0.044131,0.046948,0.041315,0.028169,0.031925,0.031925,0.023474,0.016901,0.028169,...,long sleeve,2016-12-02,0.666667,0.923077,1.0,0.998514,PE17/00004.png,yellow,acrylic,sleeveless
4,0.006573,0.098592,0.125822,0.120188,0.068545,0.046948,0.043192,0.034742,0.030047,0.029108,...,long sleeve,2016-12-02,0.666667,0.923077,1.0,0.998514,PE17/00005.png,grey,acrylic,hem

In [12]:
# Glancing at the dataset
df.info(verbose=True)

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5080 entries, 0 to 5079
Data columns (total 24 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   0              5080 non-null   float64
 1   1              5080 non-null   float64
 2   2              5080 non-null   float64
 3   3              5080 non-null   float64
 4   4              5080 non-null   float64
 5   5              5080 non-null   float64
 6   6              5080 non-null   float64
 7   7              5080 non-null   float64
 8   8              5080 non-null   float64
 9   9              5080 non-null   float64
 10  10             5080 non-null   float64
 11  11             5080 non-null   float64
 12  external_code  5080 non-null   int64
 13  season         5080 non-null   object
 14  category       5080 non-null   object
 15  release_date   5080 non-null   object
 16  day            5080 non-null   float64
 17  week           5080 non-null   float64
 18  month          5080 non-null   float64
 19  year           5080 non-null   float64
 20  image_path     5080 non-null   object
 21  color          5080 non-null   object
 22  fabric         5080 non-null   object
 23  extra          5080 non-null   object
dtypes: float64(16), int64(1), object(7)
memory usage: 952.6+ KB

Columns to keep: 
* `external_code`: Data ID
* `season`: Clothing season
* `category`: Clothing category
* `release_date`: Product release date
* `day`: 
* `week`:
* `month`:
* `year`:
* `image_path`: Path to image file
* `color`: Product color
* `fabric`: Product fabric
* `extra`:

In [20]:
# Storing new dataset with specific columns
df2 = df.iloc[:, 12:24]
df2.head()

,external_code,season,category,release_date,day,week,month,year,image_path,color,fabric,extra
0,1,SS17,long sleeve,2016-12-01,0.500000,0.923077,1.0,0.998514,PE17/00001.png,yellow,acrylic,hem
1,2,SS17,long sleeve,2016-12-01,0.500000,0.923077,1.0,0.998514,PE17/00002.png,brown,acrylic,hem
2,3,SS17,culottes,2016-12-02,0.666667,0.923077,1.0,0.998514,PE17/00003.png,blue,scuba crepe,hem
3,4,SS17,long sleeve,2016-12-02,0.666667,0.923077,1.0,0.998514,PE17/00004.png,yellow,acrylic,sleeveless
4,5,SS17,long sleeve,2016-12-02,0.666667,0.923077,1.0,0.998514,PE17/00005.png,grey,acrylic,hem

### Initial EDA

In [27]:
df["category"].value_counts()

long sleeve        1109
culottes            876
solid colours       458
sleeveless          439
short sleeves       289
doll dress          288
patterned           194
long dress          163
kimono dress        150
printed             137
trapeze dress       126
drop sleeve         122
long coat           115
short coat          113
sheath dress         84
medium coat          78
tracksuit            59
medium cardigan      50
miniskirt            37
short cardigan       36
shorts               30
shirt dress          30
maxi                 28
gitana skirt         25
long cardigan        16
long duster          15
capris               13
Name: category, dtype: int64