In [324]:
import numpy as np
import pandas as pd
import re
import matplotlib.pyplot as plt

In [325]:
df = pd.read_csv('fashion2.csv')
df

,Unnamed: 0,item_id,category,waist,size,quality,cup size,hips,bra size,height_inches,length,fit,review_summary,review_text,polarity,reviewLen,wordCount
0,8490,159891,dresses,26.0,1,5.0,a,38.0,32.0,64.0,5.0,3,This dress. Is so amazing,This dress. Is so amazing. It just arrived tod...,0.392500,301,58
1,8493,159891,dresses,31.0,8,3.0,d,41.0,36.0,62.0,5.0,3,This dress looks great on,This dress looks great on. I'm a pretty curren...,0.186250,273,57
2,8521,160625,dresses,32.0,5,5.0,a,NaN,32.0,65.0,5.0,1,Used as my wedding dress,Used as my wedding dress and I LOVED it!PROS ...,0.172436,452,85
3,8523,160625,dresses,32.0,11,4.0,d,43.0,38.0,67.0,5.0,2,"I love this dress, it's b","I love this dress, it's beautiful ! Wore this ...",0.413839,581,125
4,8524,160625,dresses,28.0,7,5.0,b,32.0,34.0,65.0,5.0,3,I love this dress!!! I bo,I love this dress!!! I bought it specifically ...,0.400769,627,117
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2092,81349,806406,outerwear,44.0,32,5.0,ddd/f,NaN,44.0,69.0,5.0,3,Great Summer Blazer,This blazer is light and airy. It will be perf...,0.299167,360,72
2093,82014,806856,outerwear,28.0,8,5.0,d,36.0,34.0,66.0,5.0,3,2 Winters and Going Strong!,I bought this coat 2 years ago when I moved fr...,0.302696,674,127
2094,82654,807252,outerwear,30.0,20,5.0,b,39.0,42.0,64.0,5.0,3,love this coat,"i got the 1x in mustard. beautiful material, t...",0.373418,232,42
2095,82655,807252,outerwear,27.0,8,4.0,b,31.0,38.0,66.0,5.0,3,I love love love this jac,I love love love this jacket and get complimen...,0.290764,124,21
2096,82720,807384,outerwear,38.0,26,5.0,c,50.0,38.0,NaN,5.0,2,Beautiful texture and colour,I was very excited to get this coat. I'm glad ...,0.224749,572,117

In [326]:
df.loc[df["review_text"].isnull() == 0]

,Unnamed: 0,item_id,category,waist,size,quality,cup size,hips,bra size,height_inches,length,fit,review_summary,review_text,polarity,reviewLen,wordCount
0,8490,159891,dresses,26.0,1,5.0,a,38.0,32.0,64.0,5.0,3,This dress. Is so amazing,This dress. Is so amazing. It just arrived tod...,0.392500,301,58
1,8493,159891,dresses,31.0,8,3.0,d,41.0,36.0,62.0,5.0,3,This dress looks great on,This dress looks great on. I'm a pretty curren...,0.186250,273,57
2,8521,160625,dresses,32.0,5,5.0,a,NaN,32.0,65.0,5.0,1,Used as my wedding dress,Used as my wedding dress and I LOVED it!PROS ...,0.172436,452,85
3,8523,160625,dresses,32.0,11,4.0,d,43.0,38.0,67.0,5.0,2,"I love this dress, it's b","I love this dress, it's beautiful ! Wore this ...",0.413839,581,125
4,8524,160625,dresses,28.0,7,5.0,b,32.0,34.0,65.0,5.0,3,I love this dress!!! I bo,I love this dress!!! I bought it specifically ...,0.400769,627,117
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2092,81349,806406,outerwear,44.0,32,5.0,ddd/f,NaN,44.0,69.0,5.0,3,Great Summer Blazer,This blazer is light and airy. It will be perf...,0.299167,360,72
2093,82014,806856,outerwear,28.0,8,5.0,d,36.0,34.0,66.0,5.0,3,2 Winters and Going Strong!,I bought this coat 2 years ago when I moved fr...,0.302696,674,127
2094,82654,807252,outerwear,30.0,20,5.0,b,39.0,42.0,64.0,5.0,3,love this coat,"i got the 1x in mustard. beautiful material, t...",0.373418,232,42
2095,82655,807252,outerwear,27.0,8,4.0,b,31.0,38.0,66.0,5.0,3,I love love love this jac,I love love love this jacket and get complimen...,0.290764,124,21
2096,82720,807384,outerwear,38.0,26,5.0,c,50.0,38.0,NaN,5.0,2,Beautiful texture and colour,I was very excited to get this coat. I'm glad ...,0.224749,572,117

In [327]:
df2 = df.loc[(df["category"] != "new") & (df["category"] != "wedding") & 
       (df["category"] != "sale")]
df2 = df2.loc[df["review_text"].isnull() == 0]
df2

,Unnamed: 0,item_id,category,waist,size,quality,cup size,hips,bra size,height_inches,length,fit,review_summary,review_text,polarity,reviewLen,wordCount
0,8490,159891,dresses,26.0,1,5.0,a,38.0,32.0,64.0,5.0,3,This dress. Is so amazing,This dress. Is so amazing. It just arrived tod...,0.392500,301,58
1,8493,159891,dresses,31.0,8,3.0,d,41.0,36.0,62.0,5.0,3,This dress looks great on,This dress looks great on. I'm a pretty curren...,0.186250,273,57
2,8521,160625,dresses,32.0,5,5.0,a,NaN,32.0,65.0,5.0,1,Used as my wedding dress,Used as my wedding dress and I LOVED it!PROS ...,0.172436,452,85
3,8523,160625,dresses,32.0,11,4.0,d,43.0,38.0,67.0,5.0,2,"I love this dress, it's b","I love this dress, it's beautiful ! Wore this ...",0.413839,581,125
4,8524,160625,dresses,28.0,7,5.0,b,32.0,34.0,65.0,5.0,3,I love this dress!!! I bo,I love this dress!!! I bought it specifically ...,0.400769,627,117
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2092,81349,806406,outerwear,44.0,32,5.0,ddd/f,NaN,44.0,69.0,5.0,3,Great Summer Blazer,This blazer is light and airy. It will be perf...,0.299167,360,72
2093,82014,806856,outerwear,28.0,8,5.0,d,36.0,34.0,66.0,5.0,3,2 Winters and Going Strong!,I bought this coat 2 years ago when I moved fr...,0.302696,674,127
2094,82654,807252,outerwear,30.0,20,5.0,b,39.0,42.0,64.0,5.0,3,love this coat,"i got the 1x in mustard. beautiful material, t...",0.373418,232,42
2095,82655,807252,outerwear,27.0,8,4.0,b,31.0,38.0,66.0,5.0,3,I love love love this jac,I love love love this jacket and get complimen...,0.290764,124,21
2096,82720,807384,outerwear,38.0,26,5.0,c,50.0,38.0,NaN,5.0,2,Beautiful texture and colour,I was very excited to get this coat. I'm glad ...,0.224749,572,117

In [363]:
df_sub = df2[['waist','hips','cup size','bra size','height_inches','size','fit']].copy()
df_sub

      waist  hips cup size  bra size  height_inches  size  fit
0      26.0  38.0        a      32.0           64.0     1    3
1      31.0  41.0        d      36.0           62.0     8    3
2      32.0   NaN        a      32.0           65.0     5    1
3      32.0  43.0        d      38.0           67.0    11    2
4      28.0  32.0        b      34.0           65.0     7    3
...     ...   ...      ...       ...            ...   ...  ...
2092   44.0   NaN    ddd/f      44.0           69.0    32    3
2093   28.0  36.0        d      34.0           66.0     8    3
2094   30.0  39.0        b      42.0           64.0    20    3
2095   27.0  31.0        b      38.0           66.0     8    3
2096   38.0  50.0        c      38.0            NaN    26    2

[2097 rows x 7 columns]

In [368]:
def get_first(s):
    
    first = s.split('/')[0]
    
    return first

In [370]:
df_sub['cup size'] = df_sub['cup size'].apply(get_first)

In [378]:
df_sub['cup size'].unique()
df_sub = df_sub.loc[df_sub['cup size'] != "nan"]
df_sub['cup size'].unique()

array(['a', 'd', 'b', 'dd', 'c', 'ddd', 'h', 'dddd', 'aa', 'j', 'i', 'k'],
      dtype=object)

In [332]:
def select_element(lst):
    return lst[1]

['a']

In [330]:
df_top = df_sub[['waist','cup size','bra size', 'height_inches']].copy()
df_bottom = df_sub[['waist','hips']].copy()
df_dresses = df_sub[['waist','cup size','bra size','height_inches','hips']].copy()