In [440]:
import numpy as np
import pandas as pd
import re
import matplotlib.pyplot as plt
from pathlib import Path

In [441]:
df = pd.read_csv('fashion2.csv')
df

,Unnamed: 0,item_id,category,waist,size,quality,cup size,hips,bra size,height_inches,length,fit,review_summary,review_text,polarity,reviewLen,wordCount
0,8490,159891,dresses,26.0,1,5.0,a,38.0,32.0,64.0,5.0,3,This dress. Is so amazing,This dress. Is so amazing. It just arrived tod...,0.392500,301,58
1,8493,159891,dresses,31.0,8,3.0,d,41.0,36.0,62.0,5.0,3,This dress looks great on,This dress looks great on. I'm a pretty curren...,0.186250,273,57
2,8521,160625,dresses,32.0,5,5.0,a,NaN,32.0,65.0,5.0,1,Used as my wedding dress,Used as my wedding dress and I LOVED it!PROS ...,0.172436,452,85
3,8523,160625,dresses,32.0,11,4.0,d,43.0,38.0,67.0,5.0,2,"I love this dress, it's b","I love this dress, it's beautiful ! Wore this ...",0.413839,581,125
4,8524,160625,dresses,28.0,7,5.0,b,32.0,34.0,65.0,5.0,3,I love this dress!!! I bo,I love this dress!!! I bought it specifically ...,0.400769,627,117
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2092,81349,806406,outerwear,44.0,32,5.0,ddd/f,NaN,44.0,69.0,5.0,3,Great Summer Blazer,This blazer is light and airy. It will be perf...,0.299167,360,72
2093,82014,806856,outerwear,28.0,8,5.0,d,36.0,34.0,66.0,5.0,3,2 Winters and Going Strong!,I bought this coat 2 years ago when I moved fr...,0.302696,674,127
2094,82654,807252,outerwear,30.0,20,5.0,b,39.0,42.0,64.0,5.0,3,love this coat,"i got the 1x in mustard. beautiful material, t...",0.373418,232,42
2095,82655,807252,outerwear,27.0,8,4.0,b,31.0,38.0,66.0,5.0,3,I love love love this jac,I love love love this jacket and get complimen...,0.290764,124,21
2096,82720,807384,outerwear,38.0,26,5.0,c,50.0,38.0,NaN,5.0,2,Beautiful texture and colour,I was very excited to get this coat. I'm glad ...,0.224749,572,117

In [442]:
df.loc[df["review_text"].isnull() == 0]

,Unnamed: 0,item_id,category,waist,size,quality,cup size,hips,bra size,height_inches,length,fit,review_summary,review_text,polarity,reviewLen,wordCount
0,8490,159891,dresses,26.0,1,5.0,a,38.0,32.0,64.0,5.0,3,This dress. Is so amazing,This dress. Is so amazing. It just arrived tod...,0.392500,301,58
1,8493,159891,dresses,31.0,8,3.0,d,41.0,36.0,62.0,5.0,3,This dress looks great on,This dress looks great on. I'm a pretty curren...,0.186250,273,57
2,8521,160625,dresses,32.0,5,5.0,a,NaN,32.0,65.0,5.0,1,Used as my wedding dress,Used as my wedding dress and I LOVED it!PROS ...,0.172436,452,85
3,8523,160625,dresses,32.0,11,4.0,d,43.0,38.0,67.0,5.0,2,"I love this dress, it's b","I love this dress, it's beautiful ! Wore this ...",0.413839,581,125
4,8524,160625,dresses,28.0,7,5.0,b,32.0,34.0,65.0,5.0,3,I love this dress!!! I bo,I love this dress!!! I bought it specifically ...,0.400769,627,117
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2092,81349,806406,outerwear,44.0,32,5.0,ddd/f,NaN,44.0,69.0,5.0,3,Great Summer Blazer,This blazer is light and airy. It will be perf...,0.299167,360,72
2093,82014,806856,outerwear,28.0,8,5.0,d,36.0,34.0,66.0,5.0,3,2 Winters and Going Strong!,I bought this coat 2 years ago when I moved fr...,0.302696,674,127
2094,82654,807252,outerwear,30.0,20,5.0,b,39.0,42.0,64.0,5.0,3,love this coat,"i got the 1x in mustard. beautiful material, t...",0.373418,232,42
2095,82655,807252,outerwear,27.0,8,4.0,b,31.0,38.0,66.0,5.0,3,I love love love this jac,I love love love this jacket and get complimen...,0.290764,124,21
2096,82720,807384,outerwear,38.0,26,5.0,c,50.0,38.0,NaN,5.0,2,Beautiful texture and colour,I was very excited to get this coat. I'm glad ...,0.224749,572,117

In [443]:
df2 = df.loc[(df["category"] != "new") & (df["category"] != "wedding") & 
       (df["category"] != "sale")]
df2 = df.loc[df["review_text"].isnull() == 0]

In [444]:
df2['cup size'] = df2['cup size'].astype(str)

In [445]:
df2

,Unnamed: 0,item_id,category,waist,size,quality,cup size,hips,bra size,height_inches,length,fit,review_summary,review_text,polarity,reviewLen,wordCount
0,8490,159891,dresses,26.0,1,5.0,a,38.0,32.0,64.0,5.0,3,This dress. Is so amazing,This dress. Is so amazing. It just arrived tod...,0.392500,301,58
1,8493,159891,dresses,31.0,8,3.0,d,41.0,36.0,62.0,5.0,3,This dress looks great on,This dress looks great on. I'm a pretty curren...,0.186250,273,57
2,8521,160625,dresses,32.0,5,5.0,a,NaN,32.0,65.0,5.0,1,Used as my wedding dress,Used as my wedding dress and I LOVED it!PROS ...,0.172436,452,85
3,8523,160625,dresses,32.0,11,4.0,d,43.0,38.0,67.0,5.0,2,"I love this dress, it's b","I love this dress, it's beautiful ! Wore this ...",0.413839,581,125
4,8524,160625,dresses,28.0,7,5.0,b,32.0,34.0,65.0,5.0,3,I love this dress!!! I bo,I love this dress!!! I bought it specifically ...,0.400769,627,117
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2092,81349,806406,outerwear,44.0,32,5.0,ddd/f,NaN,44.0,69.0,5.0,3,Great Summer Blazer,This blazer is light and airy. It will be perf...,0.299167,360,72
2093,82014,806856,outerwear,28.0,8,5.0,d,36.0,34.0,66.0,5.0,3,2 Winters and Going Strong!,I bought this coat 2 years ago when I moved fr...,0.302696,674,127
2094,82654,807252,outerwear,30.0,20,5.0,b,39.0,42.0,64.0,5.0,3,love this coat,"i got the 1x in mustard. beautiful material, t...",0.373418,232,42
2095,82655,807252,outerwear,27.0,8,4.0,b,31.0,38.0,66.0,5.0,3,I love love love this jac,I love love love this jacket and get complimen...,0.290764,124,21
2096,82720,807384,outerwear,38.0,26,5.0,c,50.0,38.0,NaN,5.0,2,Beautiful texture and colour,I was very excited to get this coat. I'm glad ...,0.224749,572,117

In [446]:
def get_first(s):
    
    first = s.split('/')[0]
    
    return first

In [447]:
df2['cup size'] = df2['cup size'].apply(get_first)

In [448]:
df2['cup size'].unique()
df2 = df2.loc[df_sub['cup size'] != "nan"]
sorted(df2['cup size'].unique())

['a', 'aa', 'b', 'c', 'd', 'dd', 'ddd', 'dddd', 'h', 'i', 'j', 'k', 'nan']

In [449]:
def select_element(lst):
    return lst[1]

In [450]:
df2['category'].unique()

array(['dresses', 'tops', 'bottoms', 'outerwear'], dtype=object)

In [451]:
df2.loc[df2['cup size'] == 'aa', 'cup size'] = 1
df2.loc[df2['cup size'] == 'a', 'cup size'] = 2
df2.loc[df2['cup size'] == 'b', 'cup size'] = 3
df2.loc[df2['cup size'] == 'c', 'cup size'] = 4
df2.loc[df2['cup size'] == 'd', 'cup size'] = 5
df2.loc[df2['cup size'] == 'dd', 'cup size'] = 6
df2.loc[df2['cup size'] == 'ddd', 'cup size'] = 7
df2.loc[df2['cup size'] == 'dddd', 'cup size'] = 8
df2.loc[df2['cup size'] == 'h', 'cup size'] = 9
df2.loc[df2['cup size'] == 'i', 'cup size'] = 10
df2.loc[df2['cup size'] == 'j', 'cup size'] = 11
df2.loc[df2['cup size'] == 'k', 'cup size'] = 12

sorted(df_sub['cup size'].unique())

[1, 2, 3, 4]

In [452]:
df2.loc[df_sub['category'] == 'dresses', 'category'] = 1
df2.loc[df_sub['category'] == 'tops', 'category'] = 2
df2.loc[df_sub['category'] == 'bottoms', 'category'] = 3
df2.loc[df_sub['category'] == 'outerwear', 'category'] = 4

df2['category'].unique()

df2

,Unnamed: 0,item_id,category,waist,size,quality,cup size,hips,bra size,height_inches,length,fit,review_summary,review_text,polarity,reviewLen,wordCount
0,8490,159891,dresses,26.0,1,5.0,2,38.0,32.0,64.0,5.0,3,This dress. Is so amazing,This dress. Is so amazing. It just arrived tod...,0.392500,301,58
1,8493,159891,dresses,31.0,8,3.0,5,41.0,36.0,62.0,5.0,3,This dress looks great on,This dress looks great on. I'm a pretty curren...,0.186250,273,57
2,8521,160625,dresses,32.0,5,5.0,2,NaN,32.0,65.0,5.0,1,Used as my wedding dress,Used as my wedding dress and I LOVED it!PROS ...,0.172436,452,85
3,8523,160625,dresses,32.0,11,4.0,5,43.0,38.0,67.0,5.0,2,"I love this dress, it's b","I love this dress, it's beautiful ! Wore this ...",0.413839,581,125
4,8524,160625,dresses,28.0,7,5.0,3,32.0,34.0,65.0,5.0,3,I love this dress!!! I bo,I love this dress!!! I bought it specifically ...,0.400769,627,117
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2092,81349,806406,outerwear,44.0,32,5.0,7,NaN,44.0,69.0,5.0,3,Great Summer Blazer,This blazer is light and airy. It will be perf...,0.299167,360,72
2093,82014,806856,outerwear,28.0,8,5.0,5,36.0,34.0,66.0,5.0,3,2 Winters and Going Strong!,I bought this coat 2 years ago when I moved fr...,0.302696,674,127
2094,82654,807252,outerwear,30.0,20,5.0,3,39.0,42.0,64.0,5.0,3,love this coat,"i got the 1x in mustard. beautiful material, t...",0.373418,232,42
2095,82655,807252,outerwear,27.0,8,4.0,3,31.0,38.0,66.0,5.0,3,I love love love this jac,I love love love this jacket and get complimen...,0.290764,124,21
2096,82720,807384,outerwear,38.0,26,5.0,4,50.0,38.0,NaN,5.0,2,Beautiful texture and colour,I was very excited to get this coat. I'm glad ...,0.224749,572,117

In [453]:
df2.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 2097 entries, 0 to 2096
Data columns (total 17 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   Unnamed: 0      2097 non-null   int64
 1   item_id         2097 non-null   int64
 2   category        2097 non-null   object
 3   waist           2097 non-null   float64
 4   size            2097 non-null   int64
 5   quality         2068 non-null   float64
 6   cup size        2097 non-null   object
 7   hips            1721 non-null   float64
 8   bra size        1913 non-null   float64
 9   height_inches   1986 non-null   float64
 10  length          2087 non-null   float64
 11  fit             2097 non-null   int64
 12  review_summary  2097 non-null   object
 13  review_text     2097 non-null   object
 14  polarity        2097 non-null   float64
 15  reviewLen       2097 non-null   int64
 16  wordCount       2097 non-null   int64
dtypes: float64(7), int64(6), object(4)
memory usage: 294.9+ KB

In [454]:
filepath = Path("/Users/christinaorengo/Documents/VenusHacks/fashion3.csv")
filepath.parent.mkdir(parents=True, exist_ok=True)
df2.to_csv(filepath)